model:
  backbone: resnet18
  embed_dim: 256
  proj_bn: true
  proj_hidden: 256

loss:
  use_nce: true
  use_triplet: true
  use_proto: true
  temperature: 0.07
  triplet_margin: 0.2
  proto_weight: 0.3

train:
  optimizer: adamw
  lr: 3.0e-4
  weight_decay: 0.05
  batch_size: 128
  epochs: 10
  ema_decay: 0.0
  num_workers: 4
  log_interval: 50
  save_every: 1

seed: 42
output_dir: results
